### ISSUE TITLE
Add a "consume remaining bytes" serializer?

### ISSUE THREAD

**Issue by svirpridon** [lojack5/structured#45]
Hi, I'm attempting to use structured to decode a networking protocol for a game. One of the, ahem, unique things the protocol includes is a "read to the end of the packet into a buffer." The game hides it behind a flag (so, `LookbackDecider` with a union including `NullSerializer`), but even if you ignore that, a use case still stands if you only care about the structure of the start of the data:

```
class Header(Structured):
    data: uint8
    needed: uint32
    everything_else: ConsumeAllRemainingBytesSerializer
```

Without having looked at code, this looks like it'd be doable via a custom `Serializer`.

Is this something that you think belongs in the library, or should I just build this on my own?

Thanks!

**Comment by lojack5** [comment]
Hey, glad you've found this useful!

Sounds like an interesting problem.  If you want to give it a go and see if you can code up a Serializer for it, then submit it I'd be happy to add it.  Otherwise, I can take a look (probably won't have much time til the new year).

One thing to note on this particular problem, it sounds like the buffer protocol methods (the `pack_into` and `unpack_from` variants) might not be able to work this way.  They buffer protocol specifies a length of the buffer at the CPython level, but the `struct` module has no equivalent "consume all the bytes" specifier.  This would mean I'd have to code up an equivalent, meaning writing CPython code rather than pure python.  Anyway, a way around this would be to make a note of it in the docstrings and have those methods raise an exception.  There *may* be some way to work around this bit by wrapping the object with a mmap but I'm unsure at the moment.

**Comment by svirpridon** [comment]
Yeah, I figured there would have to be some `NotImplementedError` or similar out of those.

I ran into a problem with a decider based approach as trying to use the `NullSerializer` leads to errors.

I'm starting to conclude the protocol is enough of a mess it might be easier to just write a bespoke serde, to match the bespoke protocol. Gotta love the '90s.

**Comment by lojack5** [comment]
Had a little time to look at this, it actually seems for the buffer protocol methods if the object gets wrapped in a `memoryview`, then we have access to the length parameter, so no issues there.

I'm thinking probably the way to implement this that fits in best is allow `math.inf` to be passed in to the `char` serializer, triggering consuming all remaining bytes.  I'll be home in a few days and can take a crack at it, what do you think (even if you don't end up using it because as you mentioned).  Although I'd be more than happy to keep adding things as you find the need if you want to keep at it.

**Comment by svirpridon** [comment]
As I dug deeper, I ended up finding structure within "all remaining bytes" -- although I did that after converting to my own python-struct-based decoding.

With that structure I think I might be able to convert back to using structured as is, although I wouldn't be too surprised to find a use in this for "and consume all remaining bytes" in the future, given this protocol. (there's no real docs on the protocol, of course!)

I like the `math.inf` as a specifier for it though.

**Comment by lojack5** [comment]
I know the feeling :) My usual motivation for adding something new here is running into some new case it doesn't handle while working with various file formats (Bethesda games plugin format is a great place for inspiration).

If you're interested, check out [this branch](/lojack5/structured/tree/45-consume-all) - all the basic functionality is there (turned out quite easy) but I've got various backend things to finish up before merging it (docs/test/etc, plus maybe leveraging `memoryview` to make some *other* serializers more correct in the buffer protocol case).

**Comment by svirpridon** [comment]
I took a poke at using structured and it went great until I got to where I needed `Array[math.inf, RepeatedType]`. So yeah, I did run back into "and consume all remaining bytes" -- but as a repeating list-until-end-of-buffer `RepeatedType`. `RepeatedType` is variable-length, so there's no quick and easy math to compute how many based on buffer length. Nor of course does it send a count of the items. Just raw items here you go. Bytes were too precious to waste on that I guess.

I could use the consume-all-bytes parse that byte blob by itself, but having two structure specifications is kinda gross.

**Comment by lojack5** [comment]
Hadn't thought about that, but I could probably add the `math.inf` semantics to the `array` serializer as well.  That might take a bit longer as that one's quite a bit more complicated, and has built in assumptions on either knowing or easily quickly finding out how many elements to unpack.  Plus since each object in the array isn't simply one byte it'll run into the case of "if there's not *exactly* the correct amount of bytes to unpack another element, errors abound".

Anyway, I'll see what I can whip up initially then think more on the edge case stuff.

**Comment by lojack5** [comment]
Implemented this, but broke off the idea of doing something similar with arrays to #60
