### ISSUE TITLE
Leftover debug statement in serializers.structs.py

### ISSUE THREAD

**Issue by davidcurie** [lojack5/structured#48]
**Describe the bug**
A print statement appears after every invocation of a Structured serializer when run as part of a script.

**To Reproduce**
```bash
user@computer $ python my_serializer_unpacker_script.py
Compute num values: <structured.serializers.structs.StructSerializer object at 0x10c5e0a70> 19s 19
```

**Expected behavior**
No extra print statement on execution.

**Desktop (please complete the following information):**
 - OS agnostic
 - Replicated in python 3.11, 3.12

**Additional context**
Appears after commit 5c651ef (#47).
I suspect this is a leftover print statement from debugging efforts.
<https://github.com/lojack5/structured/blob/36bb95c1ae7f2ce5c8f6a3b2b98d2a1e202e47ce/structured/serializers/structs.py#L46>

**Comment by lojack5** [comment]
Yep thanks, I noticed that myself today while working on a better `typing.Self` solution (recursion is making me have to fixup lots of places that assumed no recursion was happening). It was indeed from debugging (turns out the `struct.Struct.__init__` wasn't being called due to how they changed things back from some weirdness in the RCs in py 3.12.
